name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -I https://taskprism.streamlit.app
